name: authentication_client

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "flutter_news_example/packages/authentication_client/authentication_client/**"
      - ".github/workflows/authentication_client.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 3.0.2
      working_directory: flutter_news_example/packages/authentication_client/authentication_client
